// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class Booking_Guest_Mapping_Info
{
    public int Id { get; set; }

    public int? Booking_Id { get; set; }

    public int? Guest_Id { get; set; }
}