// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class Booking_Info
{
    public int Id { get; set; }

    public int? Room_Id { get; set; }

    public DateTime? CheckIn_Date { get; set; }

    public DateTime? CheckOut_Date { get; set; }

    public int? Payment_Status_Id { get; set; }

    public int? Num_Guests { get; set; }

    public int? No_Of_Days { get; set; }

    public decimal? Total_Amount { get; set; }

    public decimal? Paid_Amount { get; set; }

    public decimal? Net_Amount { get; set; }

    public DateTime? Created_Date { get; set; }

    public DateTime? Modified_Date { get; set; }

    public virtual Payment_Status_Info Payment_Status { get; set; }
}