// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class Currency_Type
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Symbol { get; set; }

    public DateTime? Modify_Date { get; set; }

    public virtual ICollection<Room_Info> Room_Infos { get; set; } = new List<Room_Info>();
}