// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class Guest_Info
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Passport_No { get; set; }

    public int? Gender_Id { get; set; }

    public DateTime? Created_Date { get; set; }

    public virtual Guest_Info Gender { get; set; }

    public virtual ICollection<Guest_Info> InverseGender { get; set; } = new List<Guest_Info>();
}