// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class License
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string LicenseKey { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime ExpiryDate { get; set; }

    public bool IsActive { get; set; }
}