// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class Payment_Status_Info
{
    public int Id { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Booking_Info> Booking_Infos { get; set; } = new List<Booking_Info>();
}