// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class Role_Info
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<User_Info> User_Infos { get; set; } = new List<User_Info>();
}