// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class Room_Type_Info
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime? Modified_Date { get; set; }

    public virtual ICollection<Room_Info> Room_Infos { get; set; } = new List<Room_Info>();
}