// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class Room_Info
{
    public int Id { get; set; }

    public string Room_Name { get; set; }

    public int? Floor_Id { get; set; }

    public int? Room_Type_Id { get; set; }

    public int? Room_Status_Id { get; set; }

    public decimal? Price_Per_Day { get; set; }

    public int? Currency_Type_Id { get; set; }

    public int? Room_Capacity_Adult { get; set; }

    public int? Room_Capacity_Child { get; set; }

    public DateTime? Modify_Date { get; set; }

    public virtual ICollection<Booking_Info> Booking_Infos { get; set; } = new List<Booking_Info>();

    public virtual Currency_Type Currency_Type { get; set; }

    public virtual Floor_Info Floor { get; set; }

    public virtual Room_Status Room_Status { get; set; }

    public virtual Room_Type_Info Room_Type { get; set; }
}