// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace N_HMS.Models;

public partial class User_Info
{
    public int Id { get; set; }

    public string User_Name { get; set; }

    public string Password_Hash { get; set; }

    public int? Role_Id { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? Created_Date { get; set; }

    public virtual Role_Info Role { get; set; }
}